# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.dedistance <- function(distances, points_size) {
    .Call(`_hclust1d_dedistance`, distances, points_size)
}

.hclust1d_heapbased <- function(points, method) {
    .Call(`_hclust1d_hclust1d_heapbased`, points, method)
}

.hclust1d_single <- function(points) {
    .Call(`_hclust1d_hclust1d_single`, points)
}

heap_experiments <- function() {
    invisible(.Call(`_hclust1d_heap_experiments`))
}

.sqrt <- function(squared_distances) {
    .Call(`_hclust1d_sqrt`, squared_distances)
}

